name: run-tests

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: json, mbstring, pcntl, intl, fileinfo
          coverage: none

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: |
          composer install --no-interaction --prefer-dist --no-progress --no-suggest

      - name: Check quality code with PHPInsights
        run: |
          vendor/bin/phpinsights -n --ansi --format=github-action

      - name: Analyze code statically with PHPStan
        uses: php-actions/phpstan@v3
        with:
          command: cp .env.example .env

      - name: Execute tests
        run: |
          cp .env.example .env
          vendor/bin/pest
